DATASET:
  DATASET: 'SAMPLE_HD_Effector'
  TRAIN_EFFECTOR_H5: '/home/michas/Desktop/SAMPLE_HD/effector_4_train.h5'
  TEST_EFFECTOR_H5: '/home/michas/Desktop/SAMPLE_HD/effector_4_test.h5'
CONFIG:
  BATCH: 24
  BATCH_VAL: 24
  EPOCHS: 500
  CHECKPOINT: 2500
  NUM_WORKERS: 12
MODEL:
  IMG_ENCODER:
    FREEZE: False
    PRETRAINED: True
  MODEL: 'PositionPred'
  LOSS:
    NAME: 'L1'
DEBUG:
  VAL_SPLIT: 'test'
LOGGING:
  LOGDIR: '../outputs/pos_pred'
