DATASET:
  DATASET: 'SAMPLE_HD_Seq2seq'
  H5_INSTRUCTIONS_TRAIN: '/home/michas/Desktop/SAMPLE_HD/instructions_h5/instructions_seq_train.h5'
  H5_INSTRUCTIONS_TEST: '/home/michas/Desktop/SAMPLE_HD/instructions_h5/instructions_seq_test.h5'
  VOCAB_PATH: '/home/michas/Desktop/SAMPLE_HD/instructions_h5/vocab_seq.json'
CONFIG:
  BATCH: 256
  BATCH_VAL: 256
  CHECKPOINT: 50
  EPOCHS: 100
MODEL:
  MODEL: 'Seq2seq'
  INSTRUCTION_ENCODER:
    VOCAB_SIZE: 81
    DROPOUT: 0.5
    INPUT_DROPOUT: 0.0
    RNN_CELL: 'lstm'
  INSTRUCTION_DECODER:
    OUT_SIZE: 51
    INPUT_SIZE: 128
    RNN_CELL: 'lstm'
    DROPOUT: 0.5
    INPUT_DROPOUT: 0.0
  LOSS:
    NAME: 'CE'
DEBUG:
  VAL_SPLIT: 'test'
LOGGING:
  LOGDIR: '../outputs/seq2seq'
